### ISSUE TITLE
producer not able to send message

### ISSUE THREAD

**Issue by rishavjaiswal** [wurstmeister/kafka-docker#509] opened 2019-06-20 12:15 UTC
content of kafka-docker file is 
CHANGELOG.md  README.md         docker-compose-single-broker.yml  docker_push        start-kafka-shell.sh  versions.sh
Dockerfile    broker-list.sh    docker-compose-swarm.yml          download-kafka.sh  start-kafka.sh
LICENSE       create-topics.sh  docker-compose.yml                overrides          test

**docker ps**
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                  NAMES
144a1914d8e7        wurstmeister/zookeeper   "/bin/sh -c '/usr/..."   21 hours ago        Up 21 hours         22/tcp, 2181/tcp, 2888/tcp, 3888/tcp   kafka-docker_zookeeper_1
b9e97977b593        wurstmeister/kafka       "start-kafka.sh"         21 hours ago        Up 21 hours         0.0.0.0:9092->9092/tcp                 kafka-docker_kafka_1

**bash-4.4# kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1
--partitions 1 --topic test**
**kafka-console-producer.sh --broker-list localhost:9092 --topic test
>**
>hi
[2019-06-20 12:15:22,982] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 3 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:23,083] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 4 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:23,187] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 5 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:23,297] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 6 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:23,407] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 7 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:23,511] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 8 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:23,615] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 9 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:23,720] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 10 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:23,825] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 11 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:23,930] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 12 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:24,035] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 13 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:24,140] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 14 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:24,244] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 15 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:24,348] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 16 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:24,452] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 17 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:24,556] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 18 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-20 12:15:24,660] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 19 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
^Corg.apache.kafka.common.KafkaException: Producer closed while send in progress
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:869)

**Comment by sscaling** [comment] 2019-06-21 10:49
As a minimum to help debug these kind of issues you will need to provide the docker-compose file you are using, the commands used to start the broker. 

Connectivity requirements are described in the [Connectivity Guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity)

**Comment by rishavjaiswal** [comment] 2019-06-27 13:17
docker-compose file content is :
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/root/kafka-no-secure/kafka/config/server.properties:/opt/kafka_2.11-2.0.0/config/server.properties"

command usinmg to start broker is 
docker-compose up -d

**Comment by sscaling** [comment] 2019-06-28 09:04
The start script writes to the `server.properties` file, so I would not recommend setting this externally as you'll have split ownership.

Here is what I would expect as information when creating an issue (i.e. minimal set of steps, resources and commands to reproduce the "issue")

**docker-compose**
```
version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**steps**
1. Start zookeeper and broker `docker-compose up -d`
2. `exec` into the kafka container `docker-compose exec kafka bash`
3. Produce message using console producer
   ```
   kafka-console-producer.sh --broker-list localhost:9092 --topic test
   ```

This makes it very clear what you are doing.

---

Assuming you are in the above state, then you can inspect zookeeper to see 

```
bash-4.4# zookeeper-shell.sh zookeeper:2181
> get /brokers/ids/1001
{"listener_security_protocol_map":{"PLAINTEXT":"PLAINTEXT"},"endpoints":["PLAINTEXT://localhost:32768"],"jmx_port":-1,"host":"localhost","timestamp":"1561711560049","port":32768,"version":4}
```

Or just view the kafka logs to see

```
kafka_1      | [2019-06-28 08:45:59,138] INFO KafkaConfig values: 
kafka_1      | 	advertised.host.name = localhost
kafka_1      | 	advertised.listeners = null
kafka_1      | 	advertised.port = 32768
```

As you can see, this is the advertised port that is external to the cluster. You can verify with `docker ps`

```
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                                NAMES
fff981fb35da        e75f891b4c21             "start-kafka.sh"         8 minutes ago       Up 8 minutes        0.0.0.0:32768->9092/tcp                              kafka-docker_kafka_1
6dd578c2d8bb        wurstmeister/zookeeper   "/bin/sh -c '/usr/sb…"   8 minutes ago       Up 8 minutes        22/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp   kafka-docker_zookeeper_1
```

If you look at the [start-kafka.sh](https://github.com/wurstmeister/kafka-docker/blob/0efae8f042322e260898801fccaaf709b65dd341/start-kafka.sh#L25-L31) script - it is trying to do the right thing and configure an `advertised.port` config because you have not explicitly provided one. However, because you are using `advertised.host = localhost` the internal broker communication is broken because inside the container `localhost:32768` is not resolvable. 

So - if you read the [Connectivity Guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity) you will see this breaks the second requirement. It also gives an example of using `localhost` - specifically using the [single-broker](https://github.com/wurstmeister/kafka-docker/blob/master/docker-compose-single-broker.yml#L10) yaml file - which publishes port 9092 to the host allowing `localhost` to work.

Closing as invalid / by design.

**Closed by sscaling** 2019-06-28 09:04 UTC
Labels: missing info
