### ISSUE TITLE
Consumer fails when min.insync.replicas=2

### ISSUE THREAD

**Issue by albamoro** [wurstmeister/kafka-docker#247] opened 2018-01-10 21:18 UTC
I hope someone might be able to throw some light into this. I am using the stock wurstmeister\kafka image with docker compose. If I change min.insync.replicas from 1 to 2, my producers can still send events fine, but my consumers cannot read the topics when using the --bootstrap-server configuration rather than zookeeper (in which case they read fine). 

The consumers get stuck in the loop below:

````
2018-01-10 21:06:04 DEBUG NetworkClient:183 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] Completed connection to node 2147482644. Fetching API versions.
2018-01-10 21:06:04 DEBUG NetworkClient:183 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] Initiating API versions fetch from node 2147482644.
2018-01-10 21:06:04 DEBUG NetworkClient:189 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] Recorded API versions for node 2147482644: (Produce(0): 0 to 5 [usable: 5], Fetch(1): 0 to 6 [usable: 6], ListOffsets(2): 0 to 2 [usable: 2], Metadata(3): 0 to 5 [usable: 5], LeaderAndIsr(4): 0 to 1 [usable: 1], StopReplica(5): 0 [usable: 0], UpdateMetadata(6): 0 to 4 [usable: 4], ControlledShutdown(7): 0 to 1 [usable: 1], OffsetCommit(8): 0 to 3 [usable: 3], OffsetFetch(9): 0 to 3 [usable: 3], FindCoordinator(10): 0 to 1 [usable: 1], JoinGroup(11): 0 to 2 [usable: 2], Heartbeat(12): 0 to 1 [usable: 1], LeaveGroup(13): 0 to 1 [usable: 1], SyncGroup(14): 0 to 1 [usable: 1], DescribeGroups(15): 0 to 1 [usable: 1], ListGroups(16): 0 to 1 [usable: 1], SaslHandshake(17): 0 to 1 [usable: 1], ApiVersions(18): 0 to 1 [usable: 1], CreateTopics(19): 0 to 2 [usable: 2], DeleteTopics(20): 0 to 1 [usable: 1], DeleteRecords(21): 0 [usable: 0], InitProducerId(22): 0 [usable: 0], OffsetForLeaderEpoch(23): 0 [usable: 0], AddPartitionsToTxn(24): 0 [usable: 0], AddOffsetsToTxn(25): 0 [usable: 0], EndTxn(26): 0 [usable: 0], WriteTxnMarkers(27): 0 [usable: 0], TxnOffsetCommit(28): 0 [usable: 0], DescribeAcls(29): 0 [usable: 0], CreateAcls(30): 0 [usable: 0], DeleteAcls(31): 0 [usable: 0], DescribeConfigs(32): 0 [usable: 0], AlterConfigs(33): 0 [usable: 0], AlterReplicaLogDirs(34): 0 [usable: 0], DescribeLogDirs(35): 0 [usable: 0], SaslAuthenticate(36): 0 [usable: 0], CreatePartitions(37): 0 [usable: 0])
2018-01-10 21:06:04 INFO  AbstractCoordinator:341 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] Marking the coordinator 192.168.1.19:32782 (id: 2147482644 rack: null) dead
2018-01-10 21:06:04 DEBUG NetworkClient:189 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] Manually disconnected from 2147482644. Removed requests: .
2018-01-10 21:06:04 DEBUG AbstractCoordinator:183 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] Attempt to join group failed due to obsolete coordinator information: This is not the correct coordinator.
2018-01-10 21:06:04 DEBUG AbstractCoordinator:183 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] Sending GroupCoordinator request to broker 192.168.1.19:32780 (id: 1001 rack: null)
2018-01-10 21:06:04 DEBUG AbstractCoordinator:183 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] Received GroupCoordinator response ClientResponse(receivedTimeMs=1515618364678, latencyMs=4, disconnected=false, requestHeader=RequestHeader(apiKey=FIND_COORDINATOR, apiVersion=1, clientId=consumer-1, correlationId=32), responseBody=FindCoordinatorResponse(throttleTimeMs=0, errorMessage='null', error=NONE, node=192.168.1.19:32782 (id: 1003 rack: null)))
2018-01-10 21:06:04 INFO  AbstractCoordinator:341 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] Discovered coordinator 192.168.1.19:32782 (id: 2147482644 rack: null)
2018-01-10 21:06:04 DEBUG NetworkClient:183 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] Initiating connection to node 192.168.1.19:32782 (id: 2147482644 rack: null)
2018-01-10 21:06:04 DEBUG AbstractCoordinator:177 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] Disabling heartbeat thread
2018-01-10 21:06:04 INFO  AbstractCoordinator:336 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] (Re-)joining group
2018-01-10 21:06:04 DEBUG AbstractCoordinator:189 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] Sending JoinGroup ((type: JoinGroupRequest, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0, sessionTimeout=10000, rebalanceTimeout=300000, memberId=, protocolType=consumer, groupProtocols=org.apache.kafka.common.requests.JoinGroupRequest$ProtocolMetadata@5665c273)) to coordinator 192.168.1.19:32782 (id: 2147482644 rack: null)
2018-01-10 21:06:04 DEBUG Selector:195 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] Created socket with SO_RCVBUF = 65536, SO_SNDBUF = 131072, SO_TIMEOUT = 0 to node 2147482644
2018-01-10 21:06:04 DEBUG NetworkClient:183 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] Completed connection to node 2147482644. Fetching API versions.
2018-01-10 21:06:04 DEBUG NetworkClient:183 - [Consumer clientId=consumer-1, groupId=spark-kafka-source-7047b743-814a-4302-b8c2-ab99dec60e75--278135814-driver-0] Initiating API versions fetch from node 2147482644.
...
````

I get the same error using the kafka-console-consumer.

My image is configured as:

````
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.19
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: DEBUG, authorizerAppender
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
    depends_on:
      - zookeeper      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - backbone
````

**Comment by sscaling** [comment] 2018-03-05 09:46
@albamoro - Please can you provide the commands you are using to start both the containers and consumer (and any other relevant information) to reproduce this scenario. i.e. how you create the topics etc.

**Comment by sscaling** [comment] 2018-03-27 21:56
Closing due to staleness

**Closed by sscaling** 2018-03-27 21:56 UTC
Labels: question
