### ISSUE TITLE
using docker volumes results in 'NotLeaderForPartitionException' 

### ISSUE THREAD

**Issue by olafstauffer** [wurstmeister/kafka-docker#22] opened 2014-12-21 13:46 UTC
I'm trying to store the broker logs outside of the container in _./data_ changing this in fig.yml:

```
kafka:
    volumes:
    - ./data:/kafka 
```

This creates the directories for every broker just fine and names them according to the used port (e.g. _kafka-logs-49198_). 

Unfortunatelly every produced message results in a _NotLeaderForPartitionException_ (see below). Without the config changes everything works fine.

Would be great if anyone had a clue on how to get around this?

---

perf-test-client output: 

> kafka-producer-perf-test.sh --topic perftest --broker-list "192.168.59.103:49198" --messages 10

client output:

> [2014-12-21 14:16:23,922] WARN Produce request with correlation id 47 failed due to [perftest,0]: kafka.common.NotLeaderForPartitionException,[perftest,1]: kafka.common.NotLeaderForPartitionException (kafka.producer.async.DefaultEventHandler)
> [2014-12-21 14:16:24,034] ERROR Failed to send requests for topics perftest with correlation ids in [0,48](kafka.producer.async.DefaultEventHandler)

server output:

> kafka_1 | [2014-12-21 13:16:27,910] WARN [KafkaApi-49198] Produce request with correlation id 47 from client ProducerPerformance on partition [perftest,0] failed due to Leader not local for partition [perftest,0] on broker 49198 (kafka.server.KafkaApis)

**Comment by splix** [comment] 2015-02-20 11:11
Have exactly same issue with Docker volumes. 

On producer side:
```
Failed to send producer request with correlation id 13 to broker 1 with data for partitions [test,1]
```
On consumer side:
```
kafka.common.NotLeaderForPartitionException
```

Works fine if internal FS is used. I believe it's a Kafka issue, maybe some incompatibility with Docker NFS

**Comment by wurstmeister** [comment] 2015-02-20 15:44
Hi, 

I can't reproduce this problem.

could you please share:
- your environment (boot2docker, native linux)
- your full ```fig.yml``` 
- exact steps you've taken before you got this error (incl topic creation, restarts, etc)

could you also share the output of ```$KAFKA_HOME/bin/kafka-topics.sh --describe --topic perftest --zookeeper $ZK```

Also just to ensure it's not caused by random port assignments (https://github.com/wurstmeister/kafka-docker/issues/27) could you please check if you can get it to work with https://github.com/wurstmeister/kafka-docker/blob/master/fig-single-broker.yml as your base configuration?

Thanks

**Comment by pkadetiloye** [comment] 2015-04-11 21:55
I upgraded my docker to 1.5.0 and am wondering if this could be causing the error

````
[2015-04-11 21:46:17,543] WARN Error while fetching metadata [{TopicMetadata for topic topic ->
No partition metadata for topic topic due to kafka.common.LeaderNotAvailableException}] for topic [topic]: class kafka.common.LeaderNotAvailableException
````

**Comment by sscaling** [comment] 2018-03-29 08:25
Closing due to staleness. Not had any recent complaints of this issue.

**Closed by sscaling** 2018-03-29 08:25 UTC
