### ISSUE TITLE
Cluster ID Mismatch

### ISSUE THREAD

**Issue by klongmitre** [wurstmeister/kafka-docker#559] opened 2020-01-10 22:03 UTC
Hi - I'm new to Kafka so perhaps I'm not understanding something. First, thanks for providing this dockerized Kafka image. It works great. I have the Kafka logs volume mounted and using `docker-compose stop` and `docker-compose up -d --no-recreate` seem to be doing the trick. I am curious how one should handle data persistence a container is torn down (e.g. `docker-compose down`). It seems that all of the necessary data is still there on the docker host, but when starting the Kafka container runs into an issue where the Cluster ID does not match the id specified in meta.properties, and the Kafka container exits. Is there a way around this? Perhaps more environment variables that need to be specified in the compose file? Thanks in advance for any guidance and/or suggestions you may have.

**Comment by Fleta** [comment] 2020-01-20 09:48
Hi, I'm having same problem. 
I am using docker swarm. I configured 3 kafkas and 3 zookeepers. I'm leaving a link to the gist of docker-compose file. Check: https://gist.github.com/Fleta/f7987bc599140bb38ec00db505466da5

And the log for this issue is under below:
```
[2020-01-20 09:38:26,625] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
[2020-01-20 09:38:26,625] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper)
[2020-01-20 09:38:26,625] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
[2020-01-20 09:38:26,625] INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper)
[2020-01-20 09:38:26,625] INFO Client environment:os.version=4.4.0-87-generic (org.apache.zookeeper.ZooKeeper)
[2020-01-20 09:38:26,625] INFO Client environment:user.name=root (org.apache.zookeeper.ZooKeeper)
[2020-01-20 09:38:26,625] INFO Client environment:user.home=/root (org.apache.zookeeper.ZooKeeper)
[2020-01-20 09:38:26,625] INFO Client environment:user.dir=/ (org.apache.zookeeper.ZooKeeper)
[2020-01-20 09:38:26,625] INFO Client environment:os.memory.free=979MB (org.apache.zookeeper.ZooKeeper)
[2020-01-20 09:38:26,625] INFO Client environment:os.memory.max=1024MB (org.apache.zookeeper.ZooKeeper)
[2020-01-20 09:38:26,625] INFO Client environment:os.memory.total=1024MB (org.apache.zookeeper.ZooKeeper)
[2020-01-20 09:38:26,628] INFO Initiating client connection, connectString=192.168.0.129:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@3427b02d (org.apache.zookeeper.ZooKeeper)
[2020-01-20 09:38:26,634] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
[2020-01-20 09:38:26,639] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2020-01-20 09:38:26,645] INFO zookeeper.request.timeout value is 0. feature enabled= (org.apache.zookeeper.ClientCnxn)
[2020-01-20 09:38:26,651] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2020-01-20 09:38:26,657] INFO Opening socket connection to server 192.168.0.129/192.168.0.129:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-01-20 09:38:26,662] INFO Socket connection established, initiating session, client: /172.18.0.4:52370, server: 192.168.0.129/192.168.0.129:2181 (org.apache.zookeeper.ClientCnxn)
[2020-01-20 09:38:26,994] INFO Session establishment complete on server 192.168.0.129/192.168.0.129:2181, sessionid = 0x1004355d8f4001c, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2020-01-20 09:38:27,006] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[2020-01-20 09:38:30,777] INFO Cluster ID = gKMTPCdQQui26oDVZo-EMA (kafka.server.KafkaServer)
[2020-01-20 09:38:30,830] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.common.InconsistentClusterIdException: The Cluster ID gKMTPCdQQui26oDVZo-EMA doesn't match stored clusterId Some(K6-IRRUxSvW0GSLeNea0DA) in meta.properties. The broker is trying to join the wrong cluster. Configured zookeeper.connect may be wrong.
	at kafka.server.KafkaServer.startup(KafkaServer.scala:220)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:44)
	at kafka.Kafka$.main(Kafka.scala:84)
	at kafka.Kafka.main(Kafka.scala)
[2020-01-20 09:38:30,843] INFO shutting down (kafka.server.KafkaServer)
[2020-01-20 09:38:30,863] INFO [ZooKeeperClient Kafka server] Closing. (kafka.zookeeper.ZooKeeperClient)
[2020-01-20 09:38:31,127] INFO EventThread shut down for session: 0x1004355d8f4001c (org.apache.zookeeper.ClientCnxn)
[2020-01-20 09:38:31,127] INFO Session: 0x1004355d8f4001c closed (org.apache.zookeeper.ZooKeeper)
[2020-01-20 09:38:31,134] INFO [ZooKeeperClient Kafka server] Closed. (kafka.zookeeper.ZooKeeperClient)
[2020-01-20 09:38:31,155] INFO shut down completed (kafka.server.KafkaServer)
[2020-01-20 09:38:31,157] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
[2020-01-20 09:38:31,170] INFO shutting down (kafka.server.KafkaServer)
```

**Comment by cricket007** [comment] 2020-01-21 10:56
Sounds like you want to hard-code `BROKER_ID` rather than have it be regenerated upon container startup.

Otherwise, reboot Zookeeper as well, and that stored metadata would be cleared.

**Comment by klongmitre** [comment] 2020-01-21 15:51
I figured the setting of `KAFKA_BROKER_ID: 1` would handle that. It doesn't. 

Sample docker-compose for Kafka Broker
```
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: <broker-host>
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_LOG_RETENTION_HOURS: 3
      KAFKA_LOG_ROLL_HOURS: 1
```

**Comment by cricket007** [comment] 2020-01-21 16:04
Well, you can't scale 3 brokers of the same ID. Hence why other solutions (like Confluent or Bitnami} compose files actually use 3 separate service definitions

**Comment by klongmitre** [comment] 2020-01-21 16:08
Agreed. I'm not trying to scale the service. It's a single broker set-up. My interest is in enabling persistent data store (via volume mounts), but if the container is destroyed, the persistent store is no longer useable due to the Cluster ID mismatch.

**Comment by Fleta** [comment] 2020-01-22 02:06
@cricket007 Hello, thanks for your attention. 
In my docker-compose file, the broker.id of kafka1~3 are all different. (See my [docker-compose.yml gist](https://gist.github.com/Fleta/f7987bc599140bb38ec00db505466da5)). 
And I think it's because I don't know much about zookeeper + kafka clustering system, but I think the point on broker.id has nothing to do with this issue. If you can tell me how the issue of cluster ID is not correlated with broker.id, I will check more. Thanks again for your comment, have a nice day!

**Comment by Fleta** [comment] 2020-01-23 00:59
I found my mistake...
```
volumes:
      - /opt/data/kafka:/kafka/kafka-logs
```

`meta.properties` is stored in the container's `/kafka/kafka-logs` path. According to the docker configuration above, the `meta.properties` stored here are stored in `/opt/data/kafka` outside the container, and these files remain with or without the container or stack exiting. The problem is that if you don't delete these files, the newly created container will be referred to the `meta.properties` of the previous container. If you have the same settings as me, try deleting all files except the log folder for each partition.

**Comment by cricket007** [comment] 2020-01-23 01:07
Do you have the same volume on all three hosts? That's going to be an issue

**Comment by Fleta** [comment] 2020-01-23 01:13
@cricket007 I think no. Although the path is the same, the container is forced to be deployed on different swarm nodes. Each node is a docker engine for a different server.

**Comment by cricket007** [comment] 2020-01-23 01:33
Okay, sure. However, swarm cannot guarantee that broker.id=1 consistently has the same volume mounted. For example, restart the service, the containers are shuffled around? It's best if you make the ID associated with the host machine like the confluent Helm chart do

**Comment by klongmitre** [comment] 2020-03-11 14:38
@cricket007 - Sorry. I'm still a little confused here. If I need to recreate the Kafka container, but want to reuse the data from the last container (e.g. use a volume mount), what is the best way to do this. With a single kafka broker, I'm seeing cluster id mismatch errors as indicated above. Any guidance would be greatly appreciated.

**Comment by cricket007** [comment] 2020-03-11 15:07
AFAIK, cluster ID is stored in Zookeeper.

You'll need to persistently mount it's data as well

**Comment by klongmitre** [comment] 2020-03-11 15:19
@cricket007 - Thanks! Would that be volume mounting to `/opt/zookeeper-${ZOOKEEPER_VERSION}/conf` and `/opt/zookeeper-${ZOOKEEPER_VERSION}/data`?

**Comment by klongmitre** [comment] 2020-03-11 15:32
@cricket007  - does this help? 

```
version: '2.4'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: my-zookeeper
    ports:
      - "2181:2181"
    networks:
      - internal-kafka
  kafka:
    image: wurstmeister/kafka
    container_name: my-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: my-kafka.domain.org
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_HOURS: 3
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_LOG_ROLL_HOURS: 1
    volumes:
      - ./kafka-data:/kafka/kafka-logs
    networks:
      - kafka-network
networks:
  kafka-network:
```

**Comment by cricket007** [comment] 2020-03-11 15:42
Thanks!

And just the ZK dataDir needs mounted, not the config

**Comment by klongmitre** [comment] 2020-03-11 15:56
@cricket007  - Thanks for the quick follow-up! Since `${ZOOKEEPER_VERSION}` is hardcoded in the image (right now it's `3.4.13`), perhaps the data directory should be changed to static location in the image, or provide a version tag for the version used for `latest`?

**Comment by cricket007** [comment] 2020-03-11 16:33
Oh, didn't realize there was a version in there... 

Just so you know, you don't have to use the wurstmeister Zookeeper with the wurstmeister Kafka image. TBH, I don't even use these images myself. I've been satisfied with the Confluent ones or choose the Bitnami ones (since they support different base containers) if trying to save space

**Comment by cricket007** [comment] 2020-03-11 16:35
Also, if trying to use persistent volumes anyway, look at using Strimzi on Minikube or Minishift, as RedHat has likely solved the problems you're running into

**Comment by MrMarshall** [comment] 2020-03-26 09:53
> @cricket007 - Sorry. I'm still a little confused here. If I need to recreate the Kafka container, but want to reuse the data from the last container (e.g. use a volume mount), what is the best way to do this? With a single kafka broker, I'm seeing cluster id mismatch errors as indicated above. Any guidance would be greatly appreciated.

@klongmitre this is indeed the issue. For anyone interested: Kafka version 2.4 has introduced a check if the cluster.id matches the one stored in Zookeeper. Kafka itself stores this in meta.properties. The meta.properties shouldn't be thrown away, instead you should keep both the zookeepers logs and data so that the cluster id is persistant.

**Comment by arkanmgerges** [comment] 2020-04-01 19:18
Hi I had the same problem and I solved it, you can check my docker-compose.yml.
First, delete your current files before applying the following config. After that, you can 
docker-compose up
and 
docker-compose down
then
docker-compose up

Then you will see that your topics will remain there and the Kafka will work
The problem that I had, was the wrong zookeeper path after I changed the path, then Kafka started working.
I hope that it helps the ones that have this problem

```
---

version: '3.7'

x-zooServers: &zooServers zoo-1:12888:13888;zoo-2:22888:23888;zoo-3:32888:33888
x-kafkaZookeeperConnect: &kafkaZookeeperConnect zoo-1:12181,zoo-2:22181,zoo-3:32181


services:

  # Zookeeper servers and Kafka servers
  zoo-1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zoo-1
    ports:
      - "12181:12181"
    volumes:
      - ./data/kafkazoo/zoo1/data:/var/lib/zookeeper/data
      - ./data/kafkazoo/zoo1/log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: *zooServers

  zoo-2:
    image: confluentinc/cp-zookeeper:latest
    hostname: zoo-2
    ports:
      - "22181:22181"
    volumes:
      - ./data/kafkazoo/zoo2/data:/var/lib/zookeeper/data
      - ./data/kafkazoo/zoo2/log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: *zooServers

  zoo-3:
    image: confluentinc/cp-zookeeper:latest
    hostname: zoo-3
    ports:
      - "32181:32181"
    volumes:
      - ./data/kafkazoo/zoo3/data:/var/lib/zookeeper/data
      - ./data/kafkazoo/zoo3/log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: *zooServers

  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    ports:
      - "19092:19092"
    volumes:
      - ./data/kafkazoo/kafka1:/var/lib/kafka/data
    depends_on:
      - zoo-1
      - zoo-2
      - zoo-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: *kafkaZookeeperConnect
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_HOST_IP:-kafka-1}:19092

  kafka-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-2
    ports:
      - "29092:29092"
    volumes:
      - ./data/kafkazoo/kafka2:/var/lib/kafka/data
    depends_on:
      - zoo-1
      - zoo-2
      - zoo-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: *kafkaZookeeperConnect
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_HOST_IP:-kafka-2}:29092

  kafka-3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-3
    ports:
      - "39092:39092"
    volumes:
      - ./data/kafkazoo/kafka3:/var/lib/kafka/data
    depends_on:
      - zoo-1
      - zoo-2
      - zoo-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: *kafkaZookeeperConnect
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_HOST_IP:-kafka-3}:39092

...
```

**Comment by cricket007** [comment] 2020-04-01 22:05
Note: mulitple brokers can use one zookeeper, and running multiple brokers on one machine is generally cpu and network bound on its own

**Comment by arkanmgerges** [comment] 2020-04-01 22:13
@cricket007 Thanks for mentioning it. As an idea it’s just to demonstrate that a configuration for a cluster worked locally. Maybe using these ideas with kubernetes and building it in the cloud for some apps that need a scalable solution.

**Comment by cricket007** [comment] 2020-04-01 22:14
These images typically aren't used in such environments

https://operatorhub.io/?keyword=kafka

**Comment by arkanmgerges** [comment] 2020-04-01 22:21
@cricket007 Thanks, I didn’t know about the above website. Thank you for mentioning it.

**Comment by sscaling** [comment] 2020-08-17 13:39
Closing due to staleness.

**Closed by sscaling** 2020-08-17 13:39 UTC
