### ISSUE TITLE
WARN Connection to node 1001 could not be established. Broker may not be available.

### ISSUE THREAD

**Issue by SquirrelNinja** [wurstmeister/kafka-docker#211] opened 2017-08-21 20:22 UTC
Running this on Mac Sierra

Started this up using this config:

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "lambda1:1:1"
    volumes:
      - /Users/<user>/projects/aa_dev_kafka/docker.sock:/var/run/docker.sock
```

Everything appears to start up, however the log kafka log is full of these errors:

WARN Connection to node 1001 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)

I saw a couple of post indicating it might be a firewall issue, however I am not running a FW locally

**Comment by SquirrelNinja** [comment] 2017-08-21 20:36
I deleted the images, the local mapping, and set the docker-compose.yml file to it's stock setting and I am still getting the error.

**Comment by agolomoodysaada** [comment] 2017-08-21 20:45
I'm also experiencing this issue with
```yml
version: '3.3'
services:
  kafka:
    image: wurstmeister/kafka:0.11.0.0
    ports:
      - 9092:9092
    network_mode: host
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: DEBUG, authorizerAppender
  zookeeper:
    image: zookeeper:3.4
    ports:
      - 2181:2181
    network_mode: host
    environment:
      ZOO_MY_ID: 1
```

**Comment by Eoan242** [comment] 2017-08-22 17:13
I am new to this docker image so I assumed it had to be me doing it wrong. For the past two days I have been trying to get this running on AWS ECS. No matter what I try with every docker-compose up, it seems that the kafka broker alternates between shutting down or throwing this "warning" indefinitely.

**Comment by nickdani** [comment] 2017-08-30 16:13
Have the same issue :(

**Comment by SciTechPilgrim** [comment] 2017-09-04 18:34
I was able to Resolve this issue on my setups. It appears that this behavior is Kafka correctly reporting that it is unable to open a TCP connection to the Docker Host. There must be code changes in Kafka 0.11.0 which make this more likely to occur.

I initially observed this issue under CentOS 7. I eventually found the default firewall in CentOS 7 did not allow connection to port 9092/tcp from the Default Zone used with Docker containers. When I modified the firewall, the Kafka warnings ceased and code worked as expected. This CentOS machine worked, with the default firewall, for the previous kafka-docker (v 0.10.1.1).

I initially did NOT observe this issue under Ubuntu 16.04, but was able to make it occur by entering an incorrect ip address for KAFKA_ADVERTISED_HOST_NAME, so the host never responded.

I found it helpful to ping the Docker Host from the kafka containers to prove the host was reachable, and to run "netstat -tlpa" on the containers. Working setups showed that a TCP connection to [host id]:9092 was ESTABLISHED. Setups exhibiting this issue showed the status to be SYN_SENT, indicating the container had tried to establish the connection but the host did not complete the process.

By the way, I found working with the CentOS 7 firewall a little confusing. It seems that a new "connection" is created, in the firewall "Default Zone", when "docker-compose up" is run. Whatever zone is set as the Default Zone must be set to allow connections to 9092/tcp. Since the Default Zone is used by default, that applies the permissions more widely than I would prefer.

Of course, there could be many reasons why a container might not be able to establish a TCP connection to its host. I hope my results will be helpful to others dealing with the same issue.

**Comment by brandshaide** [comment] 2017-09-13 14:44
I was running into the exact same issue as I was changing the origin `kafka-Dockerfile` as provided by @wurstmeister to have a Ubuntu 16.0.4 LTS as the base (due to requirements of my company): 

```
#Dockerfile
FROM ubuntu:xenial
...
```
I think you guys have tried this already - have you turned off and on again ;- ) - but I was able to solve this strange issue by just stopping and then deleting all containers/images. **May** this is also the solution in your case:

```
docker stop $(ps -a -q)
docker rm $(ps -a -q) 
docker rmi $(docker images -q) 
```

**Comment by dattatre263** [comment] 2017-10-06 13:32
for me the issue was that i had not exposed the port to the host machine. I had it as 
`kafka:
     image: wurstmeister/kafka
     ports:
     - "9092"`

as against

`kafka:
     image: wurstmeister/kafka
     ports:
     - "9092:9092"`

**Comment by aleczandra** [comment] 2017-11-17 08:38
I still have the same issue on mac sierra :(

**Comment by trajakovic** [comment] 2017-11-28 19:29
Changing/exposing port(s) didn't change the thing. Error still persists. 

Talking about: (docker info)
```
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.13.13-200.fc26.x86_64
Operating System: Fedora 26 (Twenty Six)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.37GiB
...
```

**Comment by IRobL** [comment] 2018-01-29 17:11
I've been on this sort of problem for the past several days.  The solution for me was to look into the help here https://stackoverflow.com/questions/40806436/kafka-controller-could-not-connect-to-brokers and also to ensure that I had both a PLAINTEXT and an SSL listener specified, e.g... 

```
-e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${h_name}.example.com:29092,SSL://${h_name}.example.com:29093
``` 

I can't understand why a `PLAINTEXT` listener is always required, but when I check the logs, it seems as though port 29093 is being used correctly.

**Comment by sramilli** [comment] 2018-03-28 23:19
Im having the same problem in Windows 10 (Docker toolbox) with the official guide from Confluent (link below). Maybe the cause and solution are the same.

The tutorial works great, everything's fine inside docker, but when i try to connect to Kafka from a non-dockerized Java client i get:

`Connection to node 1 could not be established. Broker may not be available.`

Anyone has solved this issue?

https://docs.confluent.io/current/installation/docker/docs/quickstart.html
https://github.com/confluentinc/cp-docker-images/blob/4.0.x/examples/kafka-single-node/docker-compose.yml

**Comment by sscaling** [comment] 2018-03-29 07:57
@SquirrelNinja - this sounds like a configuration issue. Please make sure you understand the Kafka / docker networking requirements. Hopefully https://github.com/wurstmeister/kafka-docker/wiki/Connectivity will help.

Closing due to staleness.

**Closed by sscaling** 2018-03-29 07:57 UTC
Labels: question

**Comment by edwinBasZhang** [comment] 2019-07-08 03:38
My problem was wrongly configured the broker.id.
I've got 3 brokers working in the cluster, and in server.properites. I give broker 0 and broker 1 the same **broker.id**, which caused the problem.

**Comment by djamel-benamara** [comment] 2019-07-23 09:08
I the "Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available." problem too. It appears that kafka can only connect to 9092 port. I want to create multiple brokers with my yml file and I cannot create more than one broker because of the port problem. Any ideas ???

**Comment by edwinBasZhang** [comment] 2019-07-23 09:48
> I have the "Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available." problem too. It appears that kafka can only connect to 9092 port. I want to create multiple brokers with my yml file and I cannot create more than one broker because of the port problem. Any ideas ???

@djamel-benamara 
1. kafka can connect to any port that you specified in it's configuration file (server.properties) via field: listeners & advertised.listeners.
2. For each broker, you need a specific configuration file to tell that broker how to behave.

**Comment by djamel-benamara** [comment] 2019-07-23 09:57
@edwinBasZhang here is my server.properties 
admin:///var/lib/docker/overlay2/a62575c6cdb6fc2b677b43d186f6801770782ca4250721319edbd69677bc7d56/diff/etc/kafka/server.properties
and here is my docker-compose.yml file

version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:5.2.1
    ports:
      - "19092:19092"
    depends_on:
       - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

So how should edit them so I can in the .yml file create kafka-2 and kafka-3 with each one its own port ?

**Comment by sscaling** [comment] 2019-07-23 11:53
@djamel-benamara - probably want to ask on the confluent forums as you are using confluentinc/cp-kafka:5.2.1 image, not the one published from this repository.
