### ISSUE TITLE
With image updated to run Kafka server missing an error 

### ISSUE THREAD

**Issue by GladiusK** [wurstmeister/kafka-docker#358] opened 2018-07-18 09:48 UTC
hi guys!
   we update the  image today, but we got e error when we run kafka server.
   The error desc is  [ sed: can't move '/opt/kafka/config/server.propertieslLjnmk' to '/opt/kafka/config/server.properties': Resource busy]

   The image version is [wurstmeister/kafka    latest              9ddc434c9289        2 weeks ago         301MB
]
   
   we did nothing with the config but only update the image , so pls help us tks!

**Comment by sscaling** [comment] 2018-07-18 10:15
What type + version OS are you running on, and what is the version of Docker? 

We've seen similar issues before with downloaded files. On the Travis server (Ubuntu 14.04) and locally (Mac OS) this runs fine.

**Comment by sscaling** [comment] 2018-07-18 10:35
Hmm, running the same SHA image on `Mac OS 10.13.5 (17F77)` + `Docker 18.03.1-ce-mac65 (24312)`.

Have you got the full log, so I can see at what point this is failing?

**Comment by GladiusK** [comment] 2018-07-18 10:41
kafka1_1     | Error: No such container: kafka1
kafka1_1     | Excluding KAFKA_JMX_OPTS from broker config
kafka1_1     | [Configuring] 'advertised.port' in '/opt/kafka/config/server.properties'
kafka1_1     | sed: can't move '/opt/kafka/config/server.propertieslLjnmk' to '/opt/kafka/config/server.properties': Resource busy

the compose content : 
![image](https://user-images.githubusercontent.com/5304165/42876679-0004938e-8aba-11e8-83bb-bc580b23007b.png)

**Comment by sscaling** [comment] 2018-07-18 11:29
There isn't really enough information to look at anything specific. I tried by mounting through `server.properties` file, which works fine on my machine.

I'm still unclear what line is generating that error, it looks as though it's this https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L113

However, even if my mounted `server.properties` file already includes a property that is being set things still succeed.

I'm also not sure what you have configured to produce the `Error: no such container: kafka1` error. So perhaps something else is mis configured. 

I don't think I can provide any more assistance without the full log and docker-compose config - or unless you can provide some other concrete steps to reproduce.

**Comment by GladiusK** [comment] 2018-07-18 13:59
i  hava tried  a simplest config ，but still not work. 
compose config : 
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka1:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka
    hostname: kafka1
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
      - "9999:9999"
    environment:
      MQCLOUD_LOG_MODE: "true"
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/config/server.properties:/opt/kafka/config/server.properties

server.propertis:

broker.id=1
listeners=PLAINTEXT://:9092,SSL://:9093,SASL_PLAINTEXT://kafka1:9094
advertised.listeners=PLAINTEXT://kafka1:9092,SSL://kafka1:9093,SASL_PLAINTEXT://kafka1:9094

logs:
Creating network "mqcloud-kafka_default" with the default driver
Creating mqcloud-kafka_zookeeper_1 ... done
Creating mqcloud-kafka_kafka1_1    ... done
Attaching to mqcloud-kafka_zookeeper_1, mqcloud-kafka_kafka1_1
zookeeper_1  | ZooKeeper JMX enabled by default
zookeeper_1  | Using config: /opt/zookeeper-3.4.9/bin/../conf/zoo.cfg
zookeeper_1  | 2018-07-18 13:53:07,757 [myid:] - INFO  [main:QuorumPeerConfig@124] - Reading configuration from: /opt/zookeeper-3.4.9/bin/../conf/zoo.cfg
zookeeper_1  | 2018-07-18 13:53:07,769 [myid:] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
zookeeper_1  | 2018-07-18 13:53:07,769 [myid:] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 1
zookeeper_1  | 2018-07-18 13:53:07,771 [myid:] - WARN  [main:QuorumPeerMain@113] - Either no config or no quorum defined in config, running  in standalone mode
zookeeper_1  | 2018-07-18 13:53:07,786 [myid:] - INFO  [PurgeTask:DatadirCleanupManager$PurgeTask@138] - Purge task started.
zookeeper_1  | 2018-07-18 13:53:07,787 [myid:] - INFO  [main:QuorumPeerConfig@124] - Reading configuration from: /opt/zookeeper-3.4.9/bin/../conf/zoo.cfg
zookeeper_1  | 2018-07-18 13:53:07,788 [myid:] - INFO  [main:ZooKeeperServerMain@96] - Starting server
zookeeper_1  | 2018-07-18 13:53:07,800 [myid:] - INFO  [main:Environment@100] - Server environment:zookeeper.version=3.4.9-1757313, built on 08/23/2016 06:50 GMT
zookeeper_1  | 2018-07-18 13:53:07,800 [myid:] - INFO  [main:Environment@100] - Server environment:host.name=4d4aba7cd253
zookeeper_1  | 2018-07-18 13:53:07,801 [myid:] - INFO  [main:Environment@100] - Server environment:java.version=1.7.0_65
zookeeper_1  | 2018-07-18 13:53:07,801 [myid:] - INFO  [main:Environment@100] - Server environment:java.vendor=Oracle Corporation
zookeeper_1  | 2018-07-18 13:53:07,801 [myid:] - INFO  [main:Environment@100] - Server environment:java.home=/usr/lib/jvm/java-7-openjdk-amd64/jre
zookeeper_1  | 2018-07-18 13:53:07,801 [myid:] - INFO  [main:Environment@100] - Server environment:java.class.path=/opt/zookeeper-3.4.9/bin/../build/classes:/opt/zookeeper-3.4.9/bin/../build/lib/*.jar:/opt/zookeeper-3.4.9/bin/../lib/slf4j-log4j12-1.6.1.jar:/opt/zookeeper-3.4.9/bin/../lib/slf4j-api-1.6.1.jar:/opt/zookeeper-3.4.9/bin/../lib/netty-3.10.5.Final.jar:/opt/zookeeper-3.4.9/bin/../lib/log4j-1.2.16.jar:/opt/zookeeper-3.4.9/bin/../lib/jline-0.9.94.jar:/opt/zookeeper-3.4.9/bin/../zookeeper-3.4.9.jar:/opt/zookeeper-3.4.9/bin/../src/java/lib/*.jar:/opt/zookeeper-3.4.9/bin/../conf:
zookeeper_1  | 2018-07-18 13:53:07,801 [myid:] - INFO  [main:Environment@100] - Server environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
zookeeper_1  | 2018-07-18 13:53:07,801 [myid:] - INFO  [main:Environment@100] - Server environment:java.io.tmpdir=/tmp
zookeeper_1  | 2018-07-18 13:53:07,801 [myid:] - INFO  [main:Environment@100] - Server environment:java.compiler=<NA>
zookeeper_1  | 2018-07-18 13:53:07,804 [myid:] - INFO  [main:Environment@100] - Server environment:os.name=Linux
zookeeper_1  | 2018-07-18 13:53:07,805 [myid:] - INFO  [main:Environment@100] - Server environment:os.arch=amd64
zookeeper_1  | 2018-07-18 13:53:07,806 [myid:] - INFO  [main:Environment@100] - Server environment:os.version=4.9.87-linuxkit-aufs
zookeeper_1  | 2018-07-18 13:53:07,806 [myid:] - INFO  [main:Environment@100] - Server environment:user.name=root
zookeeper_1  | 2018-07-18 13:53:07,806 [myid:] - INFO  [main:Environment@100] - Server environment:user.home=/root
zookeeper_1  | 2018-07-18 13:53:07,807 [myid:] - INFO  [main:Environment@100] - Server environment:user.dir=/opt/zookeeper-3.4.9
zookeeper_1  | 2018-07-18 13:53:07,821 [myid:] - INFO  [main:ZooKeeperServer@815] - tickTime set to 2000
zookeeper_1  | 2018-07-18 13:53:07,821 [myid:] - INFO  [main:ZooKeeperServer@824] - minSessionTimeout set to -1
zookeeper_1  | 2018-07-18 13:53:07,821 [myid:] - INFO  [main:ZooKeeperServer@833] - maxSessionTimeout set to -1
zookeeper_1  | 2018-07-18 13:53:07,821 [myid:] - INFO  [PurgeTask:DatadirCleanupManager$PurgeTask@144] - Purge task completed.
zookeeper_1  | 2018-07-18 13:53:07,847 [myid:] - INFO  [main:NIOServerCnxnFactory@89] - binding to port 0.0.0.0/0.0.0.0:2181
kafka1_1     | Error: No such container: kafka1
kafka1_1     | [Configuring] 'advertised.port' in '/opt/kafka/config/server.properties'
kafka1_1     | sed: can't move '/opt/kafka/config/server.propertiesbOgaAk' to '/opt/kafka/config/server.properties': Resource busy
mqcloud-kafka_kafka1_1 exited with code 1

**Comment by sscaling** [comment] 2018-07-18 14:42
With your config, I get a completely different error

```
Error: No such container: kafka1
[Configuring] 'advertised.port' in '/opt/kafka/config/server.properties'
Excluding KAFKA_HOME from broker config
[Configuring] 'advertised.host.name' in '/opt/kafka/config/server.properties'
[Configuring] 'port' in '/opt/kafka/config/server.properties'
[Configuring] 'broker.id' in '/opt/kafka/config/server.properties'
Excluding KAFKA_VERSION from broker config
[Configuring] 'zookeeper.connect' in '/opt/kafka/config/server.properties'
[Configuring] 'log.dirs' in '/opt/kafka/config/server.properties'
[2018-07-18 14:24:24,302] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2018-07-18 14:24:24,682] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Invalid value  for configuration advertised.port: Not a number of type INT
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:722)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:469)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:462)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:986)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:989)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:969)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
	at kafka.Kafka$.main(Kafka.scala:82)
	at kafka.Kafka.main(Kafka.scala)
```

What's strange is the two separate errors you've provided have random characters in after the filename. Are you using a non-default storage driver for docker?

I'm not sure what the additional libraries you mount through are doing, or what the `MQCLOUD_LOG_MODE: "true"` environment var is for.

https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L29 is the line producing the `Error: No such container: kafka1` output.

Have you checked to make sure that the file isn't genuinely busy / open by another process (i.e. `lsof config/server.properties`)

**Comment by GladiusK** [comment] 2018-07-19 03:19
hey guys!
finally i solved this by write all the server config in the docker-compose as environment and not  use the volumes.
I still think this is a bug while use  both the volumes server.properties and the environment in the docker-compose.

Truly thanks for all u job for me

**Comment by sscaling** [comment] 2018-08-01 17:43
Closing as it looks like this specific issue is no longer a problem

**Closed by sscaling** 2018-08-01 17:43 UTC
