### ISSUE TITLE
find an error in the tutorial

### ISSUE THREAD

**Issue by Duncan-tree-zhou** [wurstmeister/kafka-docker#564] opened 2020-01-21 06:50 UTC
in the tutorial [http://wurstmeister.github.io/kafka-docker/](http://wurstmeister.github.io/kafka-docker/) use the following example:

``` linux
$KAFKA_HOME/bin/kafka-console-consumer.sh --topic=topic --zookeeper=$ZK
```
but actually `--zookeeper` is not an option for `kafka-console-consumer.sh`. it should be replace by option `--boostrap-server`. please correct it.

**Comment by cricket007** [comment] 2020-01-21 10:45
`--zookeeper` actually is an option. Both will work equally [until Zookeper is removed from Kafka](https://cwiki.apache.org/confluence/display/KAFKA/KIP-500%3A+Replace+ZooKeeper+with+a+Self-Managed+Metadata+Quorum)

**Comment by q8webmaster** [comment] 2020-02-14 15:27
> --zookeeper
I thought `--zookeeper` is deprecated as per the help menu.

**Comment by cricket007** [comment] 2020-02-14 15:31
That doesn't mean it's removed yet.

**Comment by Duncan-tree-zhou** [comment] 2020-02-24 07:26
> That doesn't mean it's removed yet.

I had checked kafka official doc. the `zookeeper.connect` config for `consumer api` is deprecated in ver 0.10.0 ([kafka doc 0.10.0, tag:consumerconfigs](http://kafka.apache.org/0100/documentation.html#consumerconfigs)) and removed in ver 2.1.0 ([kafka doc 2.1.0, tag:consumerconfigs](http://kafka.apache.org/21/documentation.html#consumerconfigs))

it means that the `--zookeeper` option would not be supported after ver 2.1.0.

i think to add a tip may avoid some misunderstanding for users.

**Comment by cricket007** [comment] 2020-02-24 14:14
Feel free to create your own PR to fix it

**Comment by sscaling** [comment] 2020-03-11 10:18
This is a duplicate of https://github.com/wurstmeister/kafka-docker/issues/407 and https://github.com/wurstmeister/kafka-docker/issues/243

**Closed by sscaling** 2020-03-11 10:18 UTC
