### ISSUE TITLE
Kafka-connect

### ISSUE THREAD

**Issue by DiSimon** [wurstmeister/kafka-docker#725] opened 2022-09-19 13:21 UTC
Hello everyone!

Did anyone use wurstmeister/kafka:2.12-2.1.1 image with an kafka-connect Image?
I am trying to use markusgulden/kafka-connect:2.12-2.2.1 but get an error during start of the tasks: 
 java.lang.NoSuchMethodError: org.apache.kafka.common.utils.Time.waitObject(Ljava/lang/Object;Ljava/util/function/Supplier;J)V

On which side could be that issue? Kafka or Kafka-connect?

Cheers,
Denis

**Comment by OneCricketeer** [comment] 2022-09-19 14:04
If the Connect image fails, then the issue is there.

You can try mine - https://github.com/OneCricketeer/apache-kafka-connect-docker

Or just use Confluent ones

**Comment by DiSimon** [comment] 2022-09-20 08:04
Your image works! Thanks a lot!

**Comment by OneCricketeer** [comment] 2022-09-24 13:46
Glad to hear. Feel free to close this issue.

**Closed as completed** 2022-09-24 14:23 UTC
